# Informations projet SonarCloud
sonar.projectKey=1Yoel26_Projet_OC_CI_CD
sonar.organization=1yoel26

# SonarCloud URL
sonar.host.url=https://sonarcloud.io

# Définitions des sources back et front
sonar.sources=back/src/main/java,front/src/app

# Répertoires des tests
sonar.tests=back/src/test/java,front/src/app

# Exclure les fichiers de test pour ne pas les analyser 2 fois
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts


# Chemins des rapports de couverture
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

# Chemin vers les classes java pour sonar
sonar.java.binaries=back/target/classes

