# Informations projet SonarCloud
sonar.projectKey=1yoel26
sonar.organization=1Yoel26

# SonarCloud URL
sonar.host.url=https://sonarcloud.io

# Définir les sources back et front
sonar.sources=back/src/main/java,front/src

# Répertoires des tests
sonar.tests=back/src/test/java,front/src

# Inclusion des fichiers de test (optionnel pour filtrer)
sonar.test.inclusions=**/*Test.java,**/*.spec.ts

# Chemins des rapports de couverture
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info

# Langages concernés
sonar.language=java,ts,js