name: CI sur le backend avec Jacoco pour le coverage

on: 
  push:
    branches: 
      - main
    paths:
      - 'back/**'
jobs: 
  lancement-test-backend:
    runs-on: ubuntu-latest

    steps:
       - name: Récupérer le code du repository
         uses: actions/checkout@v4

       - name: Installer Java
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
           java-version: '17'

       - name: Lancer les tests et générer le coverage Jacoco
         run: mvn clean verify
         working-directory: back



            