# Compiler/Lancer l'app backend
# Lancer les tests backend
# Generer le rapport de Jacoco

# Compiler/Lancer l'app frontend
# Lancer les tests front end
# Generer le rapport de Coverage

name: CI pour le Backend + Frontend

on: 
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  compilation-backend__executions-tests__generation-rapport-jacoco:

    runs-on: ubuntu-latest

    steps:
      - name: Copier le code du Repository vers la Machine Virtuelle ubuntu
        uses: actions/checkout@v4

      - name: Installer Java sur la VM ubuntu
        uses: actions/setup-java@v4
        with: 
          distribution: temurin
          java-version: 17

      - name: Executer les tests et générer le rapport avec Jacoco
        run: mvn clean verify
        working-directory: back

      - name: Télécharger le rapport Jacoco sur GitHub pour pouvoir le consulter
        uses: actions/upload-artifact@v4
        with:
          name: dossier-rapport-tests-backend-jacoco
          path: back/target/site/jacoco

      - name: Envoyer le code à SonarCloud via sonar-scanner, pour qu'il l'analyse
        run: | 
           mvn clean verify sonar:sonar \
              -Dsonar.projectKey=1Yoel26_Projet_OC_CI_CD \
              -Dsonar.organization=1yoel26 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}


        working-directory: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  compilation-frontend__executions-tests__generation-rapport-coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Copier le code du Repository vers la Machine Virtuelle ubuntu
        uses: actions/checkout@v4

      - name: Installer NodeJs sur la VM ubuntu
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: Installer les dépendances pour le Frontend
        run: npm install
        working-directory: front

      - name: Executer les tests et générer le rapport avec Coverage
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        working-directory: front

      - name: Télécharger le rapport Coverage sur GitHub pour pouvoir le consulter
        uses: actions/upload-artifact@v4
        with:
          name: dossier-rapport-tests-frontend-coverage
          path: front/bobapp/coverage

      - name: Envoyer le code à Sonar pour qu'il l'analyse
        run: npx sonar-scanner
        working-directory: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}